# cSpell:disable

# Imports
spring.config.import=classpath:config/private.properties

# Configuraciones de la aplicacion
spring.application.name=BigoBooksStock
server.port=${SERVER_PORT:8082}

# Swagger (creo)
springdoc.api-docs.enabled=false

# Base de datos
spring.datasource.url=${db.url}?user=${db.username}&password=${db.password}

# Jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Liquibase (el esquema se administra desde la libreria comun)
spring.liquibase.enabled=false